services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    networks:
      - expense-network
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: expense-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - expense-network

  redis:
    image: redis:alpine
    container_name: expense-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - expense-network

networks:
  expense-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: